Tela de login do Administrador
CarolFOliveira/squad-real-madruga-civitas-front pull request #3
Opened 2024-10-15 13:02 UTC by felipel7

Este pull request, implementa a funcionalidade de login para administradores. A página de login foi criada com as validações básicas para e-mail e senha, além de um serviço que vai ser responsável pela autenticação de administradores. Ainda falta realizar a conexão com o backend.

Funcionalidades:
- [x] Exibir feedback ao usuário quando as credencias estão erradas, conforme a regra de negócio.
- [x] Validação básica do campo de e-mail (Campo obrigatório e formato)
- [x] Validação básica do campo de senha (Campo obrigatório e tamanho mínimo e máximo)
- [x] Responsividade.
- [x] Armazenamento do token JWT no localStorage.
- [x] Exibir feedback ao usuário durante o envio do formulário. [extra]
- [x] Exibir feedback ao usuário quando ele tenta enviar o formulário sem conexão com a internet.. [extra]

Falta fazer:
- [ ] Conectar com o backend para testar o fluxo completo
- [ ] Redirecionar o usuário para a página correta (que ainda não existe), após o login

![login](https://github.com/user-attachments/assets/63f9f340-9370-4e6f-87fa-560b6e53d6f9)

2024-10-16 17:15 UTC, fabricio-newrizon requested changes
No geral ta bem legal o código, deixei algumas sugestões. Só mais um ponto, que eu acho que poderia estruturar as pastas um pouco diferente. Não entendi muito bem qual estrutura ta seguindo, existem tantas kkkk. Mas se for a `Feature-first` acho que seria algo assim: 


```
src/
└── app/
    ├── features/
    │   ├── auth/
    │   │   ├── login/
    │   │   │   ├── login.component.ts
    │   │   │   ├── login.component.html
    │   │   │   ├── login.component.scss
    │   │   │   └── login.service.ts (caso haja lógica de login específica)
    │   │   ├── password/
    │   │   │   ├── password.component.ts
    │   │   │   ├── password.component.html
    │   │   │   ├── password.component.scss
    │   │   │   └── password.service.ts (caso haja lógica de alteração de senha)
    │   │   ├── auth.module.ts
    │   │   └── auth-routing.module.ts (opcional, se você tiver rotas específicas)
    ├── shared/  (Componentes e serviços reutilizáveis)
    │   ├── components/
    │   │   ├── button/
    │   │   │   ├── button.component.ts
    │   │   │   ├── button.component.html
    │   │   │   └── button.component.scss
    │   └── shared.module.ts
    ├── app.component.ts
    ├── app.component.html
    └── app.module.ts










src/
└── app/
    ├── features/
    │   ├── auth/
    │   │   ├── login/ (ao meu ver o admin faz parte do contexto de login, então creio que poderia deixar mais genérico dessa forma, e fazer as tratativas posteriores a partir do cargo do usuário)
    │   │   │   ├── login.component.html
    │   │   │   ├── login.component.scss
    │   │   │   ├── login.component.ts
    │   │   │   └── login.service.ts (caso exista um service específico somente para o login)
    │   │   ├── services/ 
    │   │   │   ├── auth.service.ts
    │   │   │   └── jwt.service.ts (se trocar para o storage.service, iria para o shared/services)
    │   │   ├── auth-routing.modules.ts
    │   │   ├── auth.modules.ts
    │   │   └── auth.module.ts
    ├── shared/
    │   ├── components/
    │   │   ├── button/
    │   │   └── input/
    │   ├── services/
    │   │   └── util.service.ts
    │   └── shared.module.ts
    ├── app-routing.module.ts
    └── app.module.ts
    ```
    A ideia creio eu é agrupar os arquivos por funcionalidades. Creio que assim ficaria melhor, o que acha?

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/app-routing.module.ts
> +    loadChildren: () =>
Boa utilização do lazy loading no roteamento. Isso ajuda bastante a medida que o projeto cresce. Otimiza e aumenta a velocidade de carregamento das paginas uma vez que não vai carregar a aplicação por completa de uma vez.

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/core/auth/auth.service.ts
> +export interface LoginCredentials {
Percebi que as interfaces aqui estão sendo exportadas. Se a ideai é utilizar elas em outras partes da aplicação, o que acha de abstrair elas e uma nova pasta `interfaces` por exemplo.

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/core/auth/auth.service.ts
> +  login(credentials: LoginCredentials) {
Aqui faltou so documentar o método e definir seu modificador de acesso como: 'public', 'private' ou 'protected', segue o material falando um pouco sobre eles https://dev.to/doccaio/quais-as-diferencas-entre-modificadores-public-private-protected-e-abstract-no-typescript-4g33

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/core/auth/jwt.service.ts
Parabéns, muito bom o código aqui também. Faltou so documentar os métodos.

Outro ponto, esse arquivo está fazendo muita manipulação dos dados no storage do browser, o que acha de modificar ele para um `storage.service` por exemplo?

poderia criar em `core/services/storage.service.ts`. ou em `shared/services/...`

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/features/admin/pages/login/login.component.ts
> +  private handleLoginError(error: HttpErrorResponse): void {
Boa, ficou legal o tratamento de erros. É sempre importante informar ao usuário o que esta acontecendo.

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/features/admin/pages/login/login.component.ts
> +  private handleLoginSuccess(response: LoginResponse) {
faltou colocar o tipo de retorno do método

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/features/admin/pages/login/login.component.ts
> +  onSubmit($event: SubmitEvent) {
faltou o especificar o modificador e o retorno do método assim como sua documentação.

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/features/admin/pages/login/login.component.ts
> +    this.authService.login(credentials).subscribe({
Normalmente utilizamos Promises para lidar com chamadas a API. 

Se você precisa de apenas uma resposta (o que é o caso típico de chamadas API REST), Promise faz mais sentido, pois a resposta chega uma vez e é finalizada. Observable é mais útil quando você precisa de um fluxo contínuo de dados ou de múltiplas respostas ao longo do tempo.

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/shared/shared.module.ts
Seria uma boa organizar os imports por contexto, por exemplo 
```
// Libs
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
...

// Components
import { ButtonComponent } from './components/button/button.component';
import { InputComponent } from './components/input/input.component';
```

e talvez criar uma constante que recebe os componentes em uma array. Depois é só passar o spread dessa constante para as declarações.

`const COMPONENTS = [ComponentA, ComponentB,...]` e passar `declarations: [...COMPONENTS]`

2024-10-16 17:15 UTC, fabricio-newrizon commented on src/app/features/admin/pages/login/login.component.html
ficou legal o código aqui, sugestão que dou, é com respeito ao botão de submit do form. Seria uma boa que ele só seja habilitado quando os inputs estiverem ok, ou seja, o formGroup tem que estar valido. O que acha?

2024-10-16 18:50 UTC, felipel7 commented on src/app/core/auth/auth.service.ts
> +export interface LoginCredentials {
Blz, eu não sabia muito bem onde colocá-las. Estou um pouco perdido em relação ao padrão no Angular ainda. Agora, criei uma pasta chamada `interfaces` em `shared` para reutilizá-las em vários lugares, se necessário. Não sei se está certo. Ou se deveria ter criado dentro de `auth` mesmo

2024-10-16 18:51 UTC, felipel7 commented on src/app/core/auth/auth.service.ts
> +  login(credentials: LoginCredentials) {
Tranquilo, vou documentar e começar a fazer isso de agora em diante. ;)

2024-10-16 18:56 UTC, felipel7 commented on src/app/core/auth/jwt.service.ts
Ótima ideia, já até criei esse serviço de storage mais genérico para manipular qualquer coisa no LocalStorage.. Só que eu coloquei na pasta `shared/services` seguindo seu comentário anterior com a estrutura do projeto. Qualquer coisa, só avisar que eu mudo.

2024-10-16 18:58 UTC, felipel7 commented on src/app/features/admin/pages/login/login.component.ts
> +  onSubmit($event: SubmitEvent) {
Não vou esquecer mais disso daqui p/ frente kkkk

2024-10-16 19:03 UTC, felipel7 commented on src/app/features/admin/pages/login/login.component.ts
> +    this.authService.login(credentials).subscribe({
ahh entendi! Essa era uma dúvida que eu tinha. Pensei que, como o módulo HTTP do Angular retorna um observable, precisaríamos utilizar o padrão `subscribe`. Vou mudar essa implementação.

2024-10-16 19:12 UTC, felipel7 commented on src/app/shared/shared.module.ts
Devo separar apenas os componentes das bibliotecas ou também os módulos?


 Por exemplo:

```ts
// Apenas componentes...
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { SharedModule } from 'src/app/shared/shared.module';
import { AuthRoutingModule } from './auth-routing.module';

import { AdminLoginComponent } from './login/admin-login/admin-login.component';
```

ou

```ts
// Meus módulos e componentes separados do restante..
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';

import { SharedModule } from 'src/app/shared/shared.module';
import { AuthRoutingModule } from './auth-routing.module';

import { AdminLoginComponent } from './login/admin-login/admin-login.component';
```
ou ainda outra formatação nesse caso?

2024-10-16 19:23 UTC, felipel7 commented on src/app/features/admin/pages/login/login.component.html
Essa parte é um pouco mais complicada. Inicialmente era assim, o botão de submit só era habilitado quando o formulário estava válido. Porém, conversando com os PO's, chegamos a conclusão que o botão deveria ser habilitado logo de início e que se houver um erro no formulário ele só deve ser mostrado para o usuário quando ele clicar no botão de submit.

2024-10-16 20:07 UTC, felipel7 commented on src/app/features/admin/pages/login/login.component.ts
> +    this.authService.login(credentials).subscribe({
Para resolver esse problema de fluxo contínuo aberto pelo subscribe, eu poderia utilizar o operador `take` ou isso seria uma gambiarra? kkkk

Pelo que eu estou vendo aqui nas docs o toPromise foi depreciado [link](https://rxjs.dev/api/index/class/Observable#toPromise)

Dai tem esse operador take que encerra o subscribe logo em seguida [link](https://rxjs.dev/api/index/function/take).
```ts
return this.http
      .post<LoginResponse>('/api/login', credentials)
      .pipe(take(1));
``` 

Poderia utilizar ele nesse caso?

2024-10-16 20:26 UTC, felipel7 commented
Tentei seguir a estrutura que você comentou, ficou assim agora:

```bash
.
├── app
│   ├── app.component.html
│   ├── app.component.scss
│   ├── app.component.spec.ts
│   ├── app.component.ts
│   ├── app.module.ts
│   ├── app-routing.module.ts
│   ├── features
│   │   └── auth
│   │       ├── auth.module.ts
│   │       ├── auth-routing.module.ts
│   │       ├── login
│   │       │   └── admin-login
│   │       │       ├── admin-login.component.html
│   │       │       ├── admin-login.component.scss
│   │       │       └── admin-login.component.ts
│   │       └── services
│   │           └── auth.service.ts
│   └── shared
│       ├── components
│       │   ├── button
│       │   │   ├── button.component.html
│       │   │   ├── button.component.scss
│       │   │   └── button.component.ts
│       │   └── input
│       │       ├── input.component.html
│       │       ├── input.component.scss
│       │       └── input.component.ts
│       ├── interfaces
│       │   └── auth.interfaces.ts
│       ├── services
│       │   └── storage.service.ts
│       └── shared.module.ts
├── assets
├── favicon.ico
├── index.html
├── main.ts
└── styles.scss

13 directories, 25 files
```

Qualquer coisa me avisa, estou meio perdido na estrutura ainda. :)

2024-10-16 21:58 UTC, fabricio-newrizon commented on src/app/features/auth/login/admin-login/admin-login.component.html
Para ser sincero eu não entendi muito a necessidade de especificar o 'admin' no login aqui xD. Porque o login ao meu ver é apenas uma autentificação para acessar a plataforma, e a partir dos dados do usuário que normalmente inclui o cargo dele ( 'admin', 'cliente' entre outros. Não lembro qual ficou determinado por vocês no projeto) e que será feito toda uma ocultação das features dependendo das permissões referentes ao cargo. 

No contexto, creio que poderia ficar apenas `login.component` . Creio que futuramente vai ter outros componentes que vão fazer parte do contexto de `auth` como por exemplo 'recuperação de senha'.

O que você acha?

2024-10-16 21:58 UTC, fabricio-newrizon commented on src/app/app-routing.module.ts
> +    path: 'login',
Referente ao toda  estruturação feita, o que acha de deixar o path aqui como `path: 'auth'`? Creio que futuramente novas rotas farão parte desse contexto.

2024-10-16 21:58 UTC, fabricio-newrizon commented on src/app/features/auth/auth-routing.module.ts
> +  { path: 'administrador', component: AdminLoginComponent },
Seguindo o que havia comentado anteriormente, ficaria assim:
```
  { path: 'login', component: LoginComponent },
```

2024-10-16 21:58 UTC, fabricio-newrizon commented on src/app/shared/interfaces/auth.interfaces.ts
Assim mesmo, boa! Agora só duas sugestões: 
1 - o que acha de inciarmos o nome de uma interface com um `I`  para melhor sinalizar que o arquivo se trata de uma interface e um `T` quando utilizamos type.

2 - e normalmente criamos um arquivo para cada interface separado. Por exemplo: `ILoginResponse.ts` dentro de services. 
Agora a ideia é identificar se essas interfaces serão utilizadas globalmente, caso sejam, então esta correto em deixar elas em `shared/services`, mas caso sejam utilizadas somente na feature de `auth`, talvez move-las para dentro dela em uma nova pasta só para services (creio que ficaria mais de acordo com o 'feature first'). Mas sempre podemos fazer do jeito que acharmos atenda bem para nosso projeto. Outra forma seria em apenas criar uma pasta em interfaces representando de onde elas fazem parte, no caso ficaria `shared/services/auth/ILoginResponse.ts` por exemplo. 

Ai deixo a seu critério.

2024-10-16 21:58 UTC, fabricio-newrizon commented on src/app/shared/shared.module.ts
Salve, o ideal é separar tudo pelo contexto que ele faz parte. Components somente componentes, módulos somente módulos e assim vai... Para deixar o código mais organizado. por exemplo:

```
// Libs
import { CommonModule } from '@angular/common';
...

// Components
import { AdminLoginComponent } from './login/admin-login/admin-login.component';
...
```

2024-10-16 21:58 UTC, fabricio-newrizon commented on src/app/features/admin/pages/login/login.component.html
Entendi, se foi uma decisão de negocio, então vida que segue, mas só uma dica: PO e Cliente não são 'deuses'. Devs podem e devem opinar também. Se acha que é uma feature importante tentem negociar. As vezes nem o próprio cliente sabe o que quer exatamente. Comente com a equipe também. Duvida ou opiniões nunca são desmerecidas.

2024-10-16 22:07 UTC, fabricio-newrizon commented on src/app/features/admin/pages/login/login.component.ts
> +    this.authService.login(credentials).subscribe({
Daria certo também. Mas a questão que trabalhar com observable aumenta o nível de complexidade, teria que ter um cuidado com o dispose da stream depois, os famosos Subscription.unsubscribe. 

Ai fica a seu critério.

Uma alternativa para o toPromise() seria utilizar `firstValueFrom`, por exemplo:

```
async login(credentials: any): Promise<LoginResponse> {
  return firstValueFrom(
    this.http.post<LoginResponse>('/api/login', credentials)
  );
}
```

2024-10-17 00:56 UTC, felipel7 commented on src/app/features/admin/pages/login/login.component.ts
> +    this.authService.login(credentials).subscribe({
Ah entendi, estava lendo sobre isso e percebi que, se não fizer o unsubscribe, pode ocorrer memory leaks. Vou fazer dessa forma que você sugeriu mesmo.

2024-10-17 00:57 UTC, felipel7 commented on src/app/shared/shared.module.ts
Beleza, vou organizar tudo daqui em diante. ;)

2024-10-17 00:58 UTC, felipel7 commented on src/app/features/admin/pages/login/login.component.html
Show demais Fabrício! Dica anotada.

2024-10-17 01:11 UTC, felipel7 commented on src/app/features/auth/login/admin-login/admin-login.component.html
As telas para login do Professor e do Responsável já foram implementadas em outra branch. 
Como essas telas são bem diferentes da tela do admin, optei por fazer essa separação.
Na minha cabeça ficaria algo assim:
```
├── app
│   ├── ...
│   ├── features
│   │   └── auth
│   │       ├── ...
│   │       └── login
│   │           ├── admin-login
│   │           └── user-login

```

Não tenho certeza se nas outras telas o login é realizado com e-mail e senha. Pelo que lembro, ele é feito com o número de matrícula ou algo similar. Nesse caso, talvez não seja possível reaproveitar muito da implementação atual de login em outros lugares, ou seria necessário repensar toda a lógica e refazer tudo que já foi implementado na outra branch que foi mergeada com a develop. 

Isso é uma possibilidade, mas considerando que faltam apenas 2 dias para o fim da sprint, acho que atrasaria as entregas. o que você me aconselha a fazer? 

Eu poderia criar uma nova branch apenas para resolver esse problema na próxima sprint? (Esse problema vai existir só depois que eu fizer o merge com a develop).

2024-10-17 01:14 UTC, felipel7 commented on src/app/app-routing.module.ts
> +    path: 'login',
Realmente fica melhor, vou alterar isso.

2024-10-17 01:15 UTC, felipel7 commented on src/app/shared/interfaces/auth.interfaces.ts
Vou adotar essa convenção daqui em diante. Também vou movê-la para dentro de `services` em `auth`, pois faz mais sentido, já que será usada apenas no componente de login.

2024-10-17 11:56 UTC, fabricio-newrizon requested changes
Boa, parabéns pelo trabalho. Agora com relação as interfaces, creio que deixar na pasta services não fica legal uma vez que a ideai é separar para deixar cada arquivo em seu devido lugar. Então poderia mover ela para dentro da pasta de `login` ou `auth` caso ela seja utilizada em mais mais features dentro de `auth`

2024-10-17 11:56 UTC, fabricio-newrizon commented on src/app/shared/shared.module.ts
A ideia que havia comentado anteriormente é organizar e separar os imports por contexto mas colocando o comentário como havia dado exemplo. `// Libs` e `// Components`. Não só aqui, mas onde houver import você tentaria organizar.

2024-10-17 13:02 UTC, felipel7 commented on src/app/shared/shared.module.ts
Beleza, fiz essas mudanças adicionando os comentários. Alguns arquivos como `auth.module.ts` fiquei na dúvida se devia adotar uma separação mais granular ou se poderia agrupar tudo como `// Modules` mesmo.

2024-10-17 13:04 UTC, fabricio-newrizon approved these changes

2024-10-17 20:37 UTC, fabricio-newrizon approved these changes

2024-10-17 20:38 UTC, merged