Tela Cadastro de aluno
CarolFOliveira/squad-real-madruga-civitas-front pull request #4
Opened 2024-10-18 17:17 UTC by felipel7

Este PR implementa a funcionalidade de cadastro de alunos na plataforma, incluindo validações pelo frontend.

Funcionalidades Implementadas:

- [x] Campos obrigatórios: Nome completo, RG, Número de matrícula, CPF do responsável, Turma.
- [x] Máscaras e validações para RG (xx.xxx.xxx-x) e CPF (xxx.xxx.xxx-xx).
- [x] Feedback ao usuário com snackbar para confirmações e erros.
- [x] Layout responsivo.
 
 Falta Implementar antes do merge:
 
- [ ] Integração completa com o backend para salvar os dados.
- [ ] Redirecionamento para a tela (que ainda não existe) após cadastro concluído.
- [ ] Integrar as opções do select com valores obtidos do backend.

2024-10-26 18:30 UTC, fabricio-newrizon requested changes

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/app-routing.module.ts
> +    path: 'administrador',
Salve, porque foi necessário essa rota? O administrador não faz parte de `auth`? Não entendi o porque de manter duas rotas diferentes para administrador. Se a intensão era somente ficar mais fácil para desenvolver a pagina, lembre sempre de remover quando terminar.

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/admin-routing.module.ts
> +const routes: Routes = [
Na rota principal (''), ele usa children para definir o DashboardComponent. Embora isso funcione, a rota '' com children pode confundir em algumas situações. Uma alternativa seria:

```
const routes: Routes = [
  {
    path: '',
    component: LayoutComponent,
    children: [
      { path: '', component: DashboardComponent },
      { path: 'registrar/aluno', component: StudentRegistrationComponent }
    ],
  },
];
```

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/admin.module.ts
> +  imports: [
aqui poderia seguir a mesma ideia do `const COMPONENTS ...`

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/components/brand-link/brand-link.component.ts
Boa, só uma sugestão:  separar o HTML e o CSS vai deixar o código mais modular e fácil de entender, e é uma boa prática no Angular, especialmente para componentes que podem evoluir com o tempo.

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/components/layout/layout.component.ts
> +  isMobile = false;
Apesar do modificador de acesso default ser `public` é sempre uma boa deixar ele explicito nas variáveis e nos métodos da classe.

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/components/layout/layout.component.ts
> +  ngOnInit(): void {
Mesma coisa do comentário anterior, e também seria uma boa documentar o método aqui. Para saber o que esta sendo feito.

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/components/sidebar/sidebar.component.ts
> +  menuItems: IMenuItem[] = [
Mesma coisa com relação aos modificadores de acesso, vale a pena dar uma estudada sobre eles e saber quando seria interessante utilizar cada um.

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/components/sidebar/sidebar.component.ts
> +   *
Acho que pode remover uma linha aqui.

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/components/toolbar/toolbar.component.ts
Mesma coisa quanto a separação dos arquivos.

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/pages/dashboard/dashboard.component.html
> +  <hgroup class="section__header">
o `<hgroup>` foi depreciado no HTML5, entao creio que seja uma boa alterar ele para o `<header>` por exemplo

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/features/admin/services/student.service.ts
> +   * @param student - Os dados do aluno a ser cadastrado
aqui pode especificar somente que o @param é do tipo da interface IStudenteData;

`* @param student - objeto do tipo {@link IStudenteData}` por exemplo. 
Dessa forma deve ser possível acessar a interface a partir da descrição do método, e talvez deixar comentado na própria interface o que cada atributo faz caso seja necessário (se o próprio  nome do atributo não ficar claro).

2024-10-26 18:30 UTC, fabricio-newrizon commented on src/app/shared/services/snackbar.service.ts
> +  public openSnackBar(message: string, action?: string, duration?: number) {
faltou documentar o método

2024-10-28 13:36 UTC, felipel7 commented on src/app/features/admin/services/student.service.ts
> +   * @param student - Os dados do aluno a ser cadastrado
Realmente, ficou bem melhor. Fiz isso e documentei a interface tbm.

2024-10-28 14:14 UTC, felipel7 commented on src/app/features/admin/admin.module.ts
> +  imports: [
Feito. :)

2024-10-28 14:14 UTC, felipel7 commented on src/app/features/admin/components/brand-link/brand-link.component.ts
Blz, vou separar.

2024-10-28 14:28 UTC, felipel7 commented on src/app/app-routing.module.ts
> +    path: 'administrador',
Salvee, eu pretendia utilizar o módulo `auth`  para todos usuários somente para autentificar. Dessa forma:

```ts
/auth/administrador,
/auth/professor,
/auth/responsavel,
// ...
```
Nesse módulo do administrador eu pretendia colocar todas as funcionalidades específicas do administrador:

```ts
/administrador/registrar/aluno,
/administrador/registrar/professor,
/administrador/registrar/turma,
/administrador/''  // Dashboard/Tela inicial do adm.
// ... outras rotas do administrador
```
Apesar de ter `administrador` nas duas rotas, tanto no módulo de `auth` quanto em `administrador`, seriam coisas diferentes.

2024-10-28 14:38 UTC, felipel7 commented on src/app/features/admin/admin-routing.module.ts
> +const routes: Routes = [
Eu tenho uma dúvida. Dessa forma que você falou fica mais organizado mesmo, mas como que eu faço para esconder o layout nas rotas de cadastro, por exe: `registrar/aluno` ? 

Lá no figma, algumas telas do administrador (todas as telas de cadastro) não tem sidebar nem a toolbar que coloquei dentro do componente de layout. 

Eu pretendia fazer assim:

```ts
{ path: 'registrar/aluno', component: StudentRegistrationComponent },
{ path: 'registrar/professor', component: ... },
{ path: 'registrar/turma', component: ... },
// ... outras páginas que não precisam da sidebar...
  {
    path: '',
    component: LayoutComponent, // Componente com sidebar e toolbar
    children: [
    	{ path: '', component: DashboardComponent },
    	{ path: '/alunos', component: ... }
    	{ path: '/professores', component: ... }
    	{ path: '/turmas', component: ... }
    	// ... outras paginas que precisam da sidebar e toolbar...
    ],
  },
``` 
Como resolver esse problema de Layout no Angular? Algumas rotas de administrador tem um layout específico e outras não.

2024-11-03 18:04 UTC, fabricio-newrizon approved these changes
Salve, parabéns pelas implementações, deixei só mais algumas sugestões. Vou deixar aprovado, assim que fizer as alterações pode fazer o merge.

2024-11-03 18:04 UTC, fabricio-newrizon commented on src/app/features/admin/components/video-dialog/video-dialog.component.html
Salve, parabéns pela implementação, só mais alguns pontos de sugestão:
- notei que esta utiliza dois atributos de class, você poderia combinar eles em um único atributo, por exemplo: `<mat-dialog-content class="mat-typography video">`;
-  o que acha de adicionar um título ao iframe para melhorar a acessibilidade?
- creio que o frameborder é um atributo obsoleto em HTML5, se realmente estiver, o que acha de ajustar as bordas no próprio CSS?
- talvez adicionar o atributo loading="lazy" para melhorar o desempenho.

2024-11-03 18:04 UTC, fabricio-newrizon commented on src/app/features/admin/services/student.service.ts
> +  register(student: IStudentData): Promise<unknown> {
Faltou especificar o `public` aqui. Além disso, acho que poderia especificar o tipo da resposta que vai receber da API do que deixar algo como `unknown`. Poderia conversar com o back e decidirem o que vai ser retornado, criando assim uma interface que represente os dados da resposta, por exemplo:
```
  public register(student: IStudentData): Promise<IStudentDataResponse> { ...
```

2024-11-04 11:53 UTC, felipel7 commented on src/app/features/admin/components/video-dialog/video-dialog.component.html
Feito, realizei a implementação de todas as sugestões.

2024-11-04 11:56 UTC, felipel7 commented on src/app/features/admin/services/student.service.ts
> +  register(student: IStudentData): Promise<unknown> {
Blz, criei a interface, mas ainda preciso confirmar a estrutura da resposta com o backend.

2024-11-04 13:09 UTC, merged