Integração login admin com backend
CarolFOliveira/squad-real-madruga-civitas-front pull request #6
Opened 2024-10-22 14:35 UTC by felipel7

Este PR integra o login do administrador entre front e back, e implementa funcionalidades reutilizáveis em toda a aplicação.

- [x] Integração do login do administrador com a url correta do backend.
- [x] Correção do input para exibir erros no formulário ao tentar enviar sem preencher.
- [x] Ajustes nos redirecionamentos de rota.
- [x] Criação de um interceptador para incluir o token em todas as requisições ao backend.
- [x] Uso de observable para emitir eventos de autenticação e ajustar o layout conforme o status.
- [x] Adição de verificação extra no backend para confirmar o status de autenticação do usuário quando ele retorna ao app.

2024-10-26 19:11 UTC, fabricio-newrizon requested changes

2024-10-26 19:11 UTC, fabricio-newrizon commented on src/app/app.component.ts
> +  isAuthenticated$: BehaviorSubject<boolean>;
faltou explicitar o modificador de acesso

2024-10-26 19:11 UTC, fabricio-newrizon commented on src/app/features/auth/interceptors/auth-interceptor.ts
> +  constructor(private storageService: StorageService) {}
**Sugestão:** Apesar de não ser necessário uma vez que utilizamos o modificador de acesso, mas o que acha de alterar a nomenclatura das variáveis e métodos privados adicionando um prefixo `_`, por exemplo `private _storageService: StorageService`. Isso é uma convenção definida ao iniciar projetos, tem que ser acertado pela equipe. Minha equipe adotou essa convenção no projeto atual, e achei bem legal a ideia.

2024-10-26 19:11 UTC, fabricio-newrizon commented on src/app/features/auth/login/admin-login/admin-login.component.ts
> +      this.loginFailed = false;
Não entendi muito a ideai desse `loginFailed`, em algum momento ele é definido como `true`?

2024-10-26 19:11 UTC, fabricio-newrizon commented on src/app/features/auth/services/auth.service.ts
>    public login(credentials: ILoginRequest): Promise<ILoginResponse> {
Seria legal adicionar um tratamento de erros no método login. Assim, você pode dar um feedback melhor ao usuário caso algo dê errado.

2024-10-28 15:39 UTC, felipel7 commented on src/app/features/auth/interceptors/auth-interceptor.ts
> +  constructor(private storageService: StorageService) {}
Gostei, vou utilizar essa convenção tbm. Estou usando uma para observables, que é adicionar o sufixo $, como em `isAuthenticated$`.

2024-10-28 15:45 UTC, felipel7 commented on src/app/features/auth/services/auth.service.ts
>    public login(credentials: ILoginRequest): Promise<ILoginResponse> {
Não tenho certeza se minha lógica está correta, mas optei por tratar os erros no componente porque cada tela de login é diferente. 

O fluxo é: o componente chama o serviço -> o serviço faz a chamada à API -> o componente lida com a resposta. Achei melhor não centralizar esse tratamento de erros no serviço.

2024-10-28 18:44 UTC, felipel7 commented on src/app/features/auth/login/admin-login/admin-login.component.ts
> +      this.loginFailed = false;
Sim, dentro de `handleLoginError` ele é definido como `true`. Usei essa variável para alinhar com o design do Figma. Quando o formulário está válido, mas ocorre um erro no servidor ou as credenciais estão incorretas, devemos mostrar um ícone dentro do input e deixar o texto em vermelho, conforme a imagem:

![1](https://github.com/user-attachments/assets/57734676-f059-42a1-9167-130bcd116324)

Inicialmente minha intenção era "limpar" esse estado de erro (deixar `false` novamente) quando o usuário voltasse a interagir com o input em questão. Vou consultar os POs para decidir se vale a pena ajustar esse comportamento agora ou não. Talvez precise me aprofundar um pouco mais na parte de formulários do angular para aplicar isso da forma correta.

Bem observado, a parte do finally está realmente incorreta; coloquei para teste e já vou remover.

2024-11-03 18:07 UTC, fabricio-newrizon approved these changes

2024-11-04 11:43 UTC, merged